# Generated by Django 4.1.7 on 2023-03-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_img', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('car_price', models.CharField(max_length=100)),
            ],
        ),
    ]
