# Generated by Django 4.1.7 on 2023-03-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/cars/'),
        ),
    ]
